language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install --upgrade pip virtualenv
  - virtualenv venv
  - . venv/bin/activate

install:
  - pip install -r requirements.txt

script:
  - pythom -m pytest
